### ISSUE TITLE
Gaufrette\Adapter\AwsS3 directory options causing integration proble

### ISSUE THREAD

**Issue by mpoiriert** [KnpLabs/Gaufrette#407] opened 2016-04-24 15:57 UTC
If I am using the directory options for the Adapter when using the file system _keys_ method I will get a list of keys that are only in the directory. When calling _has_ on one of those key I will get a false return value since the directory will be prepend to it again...

I know there is _normalizePath_ method in the Local adapter, maybe this should be integrated too in the AwsS3 client

**Comment by NiR-** [comment] 2017-04-27 17:48
Hello, I tried to reproduce the error you're talking about but I'm unable to do so. Still I can confirm there're some inconsistencies. Could you provide more details about your issue please?

**Comment by mpoiriert** [comment] 2017-05-16 21:35
Maybe I was not clear for example i am using a environment for a directory "beta".
If I call keys i will get a list like this:

- beta/folder1
- beta/folder2

Than if I am calling has with the result of keys "beta/folder1" it will return false since it will check for "beta/beta/folder1"

For me it's a bug. If the directory options is implicitly use in function is should be completly transparent form the user point of view so "keys" should return:

- folder1
- folder2

Without the beta folder...

**Comment by NiR-** [comment] 2017-05-21 21:18
I added some test cases (see #491) for what you describe. Tests are green, so I can't reproduce this bug.

Digging in the code, I realized this issue has been fixed in [this commit](https://github.com/KnpLabs/Gaufrette/commit/4db00a7096a956d0287239c4fb26205ac2ad4132), two years ago (Sep. 10, 2015) and has been released in [0.2.1](https://github.com/KnpLabs/Gaufrette/releases/tag/0.2.1) (Mar. 3, 2016) and newest releases. Since you created this issue on Apr. 24, 2016, I guess you used an old release shipped with that bug.

Are you still facing the same problem?

**Comment by mpoiriert** [comment] 2017-05-23 10:59
Sorry I am not working for the company that was using this library and I am
not planning to use it in the next few months on another project.

Your hypothesis make sens, I tend to not update big library as often since
sometime they have backward compatible change and other adapter where
working properly and was really critic to our project.

I think the new lead on the project update everything to symfony 3 and all
the dependency in the last couple of month so he probably saw those at the
same time.

**Comment by NiR-** [comment] 2017-05-23 11:15
Thank you for the quick feedback :)

**Closed by NiR-** 2017-05-23 11:15 UTC
Labels: Waiting for user's input
