### ISSUE TITLE
AWS SDK about deprecated dependency warning

### ISSUE THREAD

**Issue by peter279k** [KnpLabs/Gaufrette#628] opened 2019-10-22 09:35 UTC
As title, when I install this package via `composer install` command, I got this warning message:

```
.......
Package amazonwebservices/aws-sdk-for-php is abandoned, you should avoid using it. Use aws/aws-sdk-php instead.
.......
```

It looks like this package depends on deprecated AWS SDK package.

This should be concerned and change into recommended package.

**Comment by nm2107** [comment] 2019-10-22 10:17
Thanks for reporting.

This is a duplicate of #554 .

You can help by proposing a replacement for AWS SDK ;)

**Closed by nm2107** 2019-10-22 10:17 UTC
